### ISSUE TITLE
Not working on 3.6 release ?

### ISSUE THREAD

**Issue by plagasul** [rasteiner/k3-pagesdisplay-section#10]
Hello, I just installed 3.6 on a site with pagesdisplay, older version, it returned an exception so I went and downloaded last version, un packed in place:

![image](https://user-images.githubusercontent.com/13966673/142609136-3f806b5c-ff37-467f-852e-26ff7dab004b.png)

And while there is no exception, the section does not show:

![image](https://user-images.githubusercontent.com/13966673/142609229-392504f6-c3e5-47dc-8378-d04d03697ee3.png)

This is the yaml code:

```
 shows:
    label: Shows 
    type: pagesdisplay
    query: page.includedInShows
    info: '{{page.datestart.toDate('d.m.Y')}} -> {{page.dateend.toDate('d.m.Y')}} | {{page.curator.topage.title.ifAndOr}} {{page.venue.topage.title.ifAndOr(', ')}} {{page.city}}'
    image: page.selectedimages.toFiles.first
```

Did I miss anything?

Thank you

**Comment by rasteiner** [comment]
Just tested it: the section works here on 3.6.0.

Maybe try reinstalling: 
 - delete the `site/plugins/pagesdisplay` folder
 - delete the `media/panel` folder
 - download again and extract the folder / install via composer (`composer require rasteiner/k3-pagesdisplay-section`)

**Comment by plagasul** [comment]
I took the composer route, it worked. 

I originally unpacked the downloaded release at site/plugins 

Who knows!

Thank you
