### ISSUE TITLE
Wrong submodule install path

### ISSUE THREAD

**Issue by Daandelange** [rasteiner/k3-pagesdisplay-section#11]
I ran into an issue using the submodule clone method from the readme. In `site/plugins/rasteiner/k3-pagesdisplay-section` kirby 3.6 doesn't see the plugin. I had to remove `rasteiner/` from the path when cloning.
So the readme might need a correction, I'm not sure if `plugins/vendor/plugin/` is a supported way of registering plugins anyways.

**Comment by rasteiner** [comment]
you're right of course :)

thanks for the notice
