### ISSUE TITLE
Example: Syntax Error

### ISSUE THREAD

**Issue by herrajon** [rasteiner/k3-pagesdisplay-section#2]
Missing apostrophes in your example in readme.md:

```
headline: Hest Pages
type: pagesdisplay
query: site.index.filterBy('title', '*=', 'Hest')
```

If excluded it breaks.

**Comment by rasteiner** [comment]
Yes, thanks. 
The Kirby query language syntax changed at some point. While those changes allowed us to pass variables to functions, it removed the functionality that coerced any argument to a string value.
