### ISSUE TITLE
The Toolkit\Query class has been deprecated

### ISSUE THREAD

**Issue by vauvarin** [rasteiner/k3-pagesdisplay-section#22]
With the release of Kirby 3.9.0, the Toolkit\Query class has been deprecated and should be replaced by Query\Query.

**Comment by rasteiner** [comment]
Oh.. Do you happen to know if the semantics of the new class is the same?

**Comment by vauvarin** [comment]
This is what is deprecated:

- Old Kirby\Toolkit\Query has been deprecated and will be removed in Kirby 3.10.0. Use Kirby\Query\Query instead, `e.g.Query::factory($query)->resolve($data).`
    
- new Query($query, $data): Passing $data to constructor will be deprecated. Use (`new Query($query))->resolve($data)` instead.
    
- Query::result() will be deprecated. Use `$query->resolve($data)` instead.

I think you use the `result()` method in your plugin and it should be replaced by `resolve($data)`

Check the PR here: https://github.com/getkirby/kirby/pull/4626

**Comment by rasteiner** [comment]
Thanks for the heads up :)

The latest version 0.2.4 should be compatible with kirby from 3.7.2 to 3.9.0
