### ISSUE TITLE
Respect pages with `read: false` in blueprint in `query`

### ISSUE THREAD

**Issue by bvdputte** [rasteiner/k3-pagesdisplay-section#5]
Thanks for this plugin!

I noticed when you query pages via the `query` prop it also returns pages where `read: false` has been defined in the blueprint. This let these pages show up in the pages display but results in errors when users click on them.

Could you fix? Or is there a workaround?

Thx

**Comment by rasteiner** [comment]
Oh, you're right! I would have expected Kirby to filter these out by default, but it seems it doesn't. 

Until I fix it in the code you could try something like filtering by "[isReadable](https://getkirby.com/docs/reference/objects/page/is-readable)":

```yml
query: site.myquerysofar.filterBy("isReadable", true)
```

**Comment by bvdputte** [comment]
Hi, I can confirm your intermediate solution works. Thx!
