### ISSUE TITLE
Kirby 3.6.0-beta.1 compatibility

### ISSUE THREAD

**Issue by MaluNoPeleke** [rasteiner/k3-pagesdisplay-section#9]
After updating Kirby to 3.6.0-beta.1 I got the following error while accessing the panel:

Whoops\Exception\ErrorException thrown with message "array_replace_recursive(): Expected parameter 1 to be an array, string given"

Stacktrace:
#8 Whoops\Exception\ErrorException in /var/www/virtual/peleke7/site/plugins/k3-pagesdisplay-section/src/PagesDisplaySection.php:78
#7 array_replace_recursive in /var/www/virtual/peleke7/site/plugins/k3-pagesdisplay-section/src/PagesDisplaySection.php:78
#6 require in /var/www/virtual/peleke7/site/plugins/k3-pagesdisplay-section/index.php:5
#5 include_once in /var/www/virtual/peleke7/kirby/src/Filesystem/F.php:425
#4 Kirby\Filesystem\F:loadOnce in /var/www/virtual/peleke7/kirby/src/Cms/AppPlugins.php:811
#3 Kirby\Cms\App:pluginsLoader in /var/www/virtual/peleke7/kirby/src/Cms/AppPlugins.php:782
#2 Kirby\Cms\App:plugins in /var/www/virtual/peleke7/kirby/src/Cms/AppPlugins.php:671
#1 Kirby\Cms\App:extensionsFromPlugins in /var/www/virtual/peleke7/kirby/src/Cms/App.php:130
#0 Kirby\Cms\App:__construct in /var/www/virtual/peleke7/index.php:5

This wasn't an issue with the alpha.4 before.

**Comment by rasteiner** [comment]
Can you confirm it's fixed in 0.1.1?

**Comment by MaluNoPeleke** [comment]
Yes, it is fixed, thanks a lot!
